# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35da05ab78adc304d331e32ac401467b2f3c64e277908e5bcee71fc837b18cb629e1f67026fa7430da8df4139931188ce155cb6bc105b9723ad69b79bb62a7b4

test:
  secret_key_base: d39119b83e55616f3e198e71900a342bc9391c7c1b7bd225710200489013d416a8c9dd32ef269c1474a789735faae2d5b784b39ff9cd2485b7a0d5dbb37580fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
